### ISSUE TITLE
On adding a new session, add the option to return to Sessions list

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#112]
Currently, after a user add a new session, he is returned to the "Add session" form again. This led to some confusion as user thought their session wasn't create properly. The easiest way would be, I think, to add another button "Add and display sessions" beside the actual "Add Session". And that would be consistent with other Moodle module (quiz).

copied from: https://tracker.moodle.org/browse/CONTRIB-5554

**Comment by danmarsden** [comment]
comment copied from tracker:
Yes - there are a number of areas where usability could be improved in the forms - especially around notification of changes made and making more consistent with other plugins.
I'm not actively working on these changes right now but would be happy to review any changes/patches from any third parties.
thanks!

**Comment by antonio-c-mariani** [comment]
How about always return to the list of sessions after creating a new (or more) session?

I personally do not like the current behavior where I'm redirected to a warning page telling me "the session was sucessfuly generated" to then be again redirected to another page. I prefer to be directly redirect to the sessions list, particularly because with a single click I can go back to the add session interface, if necessary. It's easy to add a message similar to the one showed on the attached image in the sessions tab, which could be generated by "$OUTPUT->notification()".

Considering this, the "sessions" tab should display all sessions when the previous done action was "add section"  (see #116). This could be done by adding the following line to sessions.php after the sections were generated:
    $SESSION->attcurrentattview[$cm->course] = ATT_VIEW_ALL;

![redirect_add](https://cloud.githubusercontent.com/assets/10731910/10320172/7f7c90f0-6c48-11e5-95d8-8d0cc8bf1755.png)

**Comment by danmarsden** [comment]
yeah - I hate those too... I'd be keen to see any improvements to remove those silly interim message pages.

**Comment by antonio-c-mariani** [comment]
I sent you a pull request that exemplifies this. The messages are stored in the $SESSION variable. This alternative uses the standard Moodle mechanism to show messages.

It's easy to include a "close" button in the message area (Bootstrap standard) but it depends on a small change on Moodle code. We'll try to submit this change to Moodle staff.

**Comment by danmarsden** [comment]
this has been sorted with Antonio's work - thanks!
