### ISSUE TITLE
Attendance Block Messaging

### ISSUE THREAD

**Issue by btindell** [danmarsden/moodle-mod_attendance#166]
In the global admin settings, if messaging is turned off, and the instructor goes to "Report", clicks on a student, and then clicks "Send a message", an error occurs. 

This wording is somewhat misleading. Perhaps this could be changed to "Send an email" instead of sending a message, or this functionality is disabled if messaging is disabled for the site.

**Comment by danmarsden** [comment]
Disabling the functionality doesn't seem right - the process still works and a "Message" is sent but is sent via e-mail instead. I suppose we could check if messaging was disabled and change the text on the button to "send an e-mail" but the Warning on the message course users page will still appear because this is a core Moodle function and not something we can control from within the Attendance code.

**Comment by btindell** [comment]
Hi Dan, I think I didnt explain this well enough. As a comparison the functionality I was going for was done by Progress Bar with Contrib-5928 (https://tracker.moodle.org/browse/CONTRIB-5928). Hope this helps.

**Comment by danmarsden** [comment]
Yeah - I don't like what Michael has done there. When Messaging is turned off you can still send "e-mails" although the message on the messaging page is a bit nasty. I'm inclined to close this as "won't fix" but If someone else wants to submit a pull request to change the text on the button when messaging is disabled that's fine by me.

**Comment by danmarsden** [comment]
I'm closing this as "won't fix" but as mentioned I'm happy if someone wants to file a pull request to change the text on the button when messaging is disabled (but I don't think we should remove the capability to send e-mails when messaging is disabled) - thanks!
