### ISSUE TITLE
Error when viewing session based on a deleted group

### ISSUE THREAD

**Issue by zoebogner** [danmarsden/moodle-mod_attendance#191]
Attempting to view or take attendance for a session set up in group mode, after that group has been deleted, returns the following error:

> Notice: Trying to get property of non-object in ./mod/attendance/take.php on line 56.
> Stack trace:
> line 56 of ./mod/attendance/take.php: PHP Notice thrown
> Exception: You can't take attendance for group "{$a}" in ./mod/attendance/take.php on line 56.
> Stack trace:
> line 56 of ./mod/attendance/take.php: moodle_exception thrown
> Page path
> 
> You can't take attendance for group "{$a}" 

As well as this error, any data already entered for these sessions is no longer visible after the group has been deleted. Since attendance is often assessed in our institution, losing data is a bit of a problem for us. We're wondering if anyone has any ideas around implementing an alternative way to display (or even restore) these orphaned sessions?

**Comment by danmarsden** [comment]
If the group no longer exists then you shouldn't be able to take attendance for that group anymore - typically when a group is deleted anything associated with that group is also deleted - but I'll tidy up the links a bit and make it clear that the group associated has been deleted.

**Comment by danmarsden** [comment]
I've pushed a fix through into the git repository that makes it clear that the session corresponds to a group that has been deleted. (and doesn't show the php errors/warnings.) We can't display the old data in the reports because when using groups we join with the groups table in Moodle and if the group has been deleted, then we can't find the users that relate to that group.

the attendance data does still exist in the database table and it's possible in future that we could look at  showing that data on the report and export pages but it's unlikely I'll work on this as a volunteer (always happy to receive well written pull requests though.)

thanks for the report!
