### ISSUE TITLE
Attendance Totals in export/move row total columns.

### ISSUE THREAD

**Issue by haietza** [danmarsden/moodle-mod_attendance#224]
We have had requests to
- Move the row totals columns to be next to the student names on the Report tab, All view
- Include the row totals in the export file

**Comment by danmarsden** [comment]
I'm not sure about moving the row total columns, but if that was configurable it might be ok. Feel free to submit a pull request - or contact me if you are able to fund the time for me to do the work. (I work for the Moodle Partner Catalyst IT)

**Comment by antonio-c-mariani** [comment]
Hi

Here are some suggestions related to the first request (see the picture below):
* Divide the header into two rows;
* Add two buttons in the sessions column, the first one to hide/show session details and the second to move the entire session details to right (after the "Taken sessions" column) and left again;
* Move the "Send a message" button to the end of the message sending column.

What do you think about this?

![attendance](https://cloud.githubusercontent.com/assets/10731910/20991468/cc39a35a-bcc5-11e6-979d-720184b9475a.png)

**Comment by danmarsden** [comment]
I'm ok with 2 rows for the header, but I'm not sure about those buttons - seems quite different from other tables in Moodle doesn't it?  often tables like this in Moodle have a "preferences" section underneath the table that allows different display options to be changed which might be better? - I haven't taken a close look at any of the newer tables in 3.2 though so if there are interface ideas we can re-use to be consistent with other forms let me know!

**Comment by antonio-c-mariani** [comment]
The inspiration was the grader report (/grade/report/grader/index.php) in which buttons are used to control the detail level of the grade aggregations. The same approch is used by mod/assign when viewing submissions to hide/show columns. The same icons are used here to hide/show session details in order to keep semantic consistency. 

When an action is related to a specific column (column sorting, hide/show details, etc) I think this approach of icones (or links) associated to the column title is better than the "preferences" section. The second approch seems better for filters and for other actions and preferences that are applyed to the overall table or to a group of columns.

**Comment by danmarsden** [comment]
I've seen the hide/show stuff before (that was fine and makes sense sorry I wasn't clear there.) but I haven't seen the arrows used to change the order of columns before - is that used somewhere else that you know of?

**Comment by danmarsden** [comment]
it does look like a cool idea to re-order the columns that way - I just want to be wary about deviating from the "normal" tables in Moodle.

**Comment by antonio-c-mariani** [comment]
I didn't find any place where the arrow has this semantic maybe because is not common to have this behaviour of changing column positions in tables.

This alternative seems to be simple and takes advantage of the fact that already exists another icon near the column label. The "preferences" section underneath the table seems to unnecessarily pollute the interface. I would then prefer to put this option in the "Settings" tab (it's necessary to redesign that interface).

No matter the interface alternative, would be interesting to save the user options (make them persistent) for both actions (hide/show and column position). Have you any suggestion about that?

**Comment by danmarsden** [comment]
persistence makes sense - many areas of Moodle do that already like filters/hiding columns etc. We do see occasional problems where a user forgets they have hidden something but I don't think there's always an easy answer for that. I'm not overly convinced we need to add it to the settings tab - and I agree with you that the preferences section under the table isn't a great interface either.

Lets just go outside the box and implement an interface like you suggested initially - if Moodle tables eventually add drag/drop support for re-ordering columns we might eventually switch to using something similar.

It may not be worth shifting the "send a message" button In future the ability to do other things to the selected users on the report may be added - not just sending a message. Also most other forms in Moodle have the checkbox on the left - seems to be nicer to tie to to the users "name" rather than the data at the end of the column.

thanks for the discussion!

**Comment by haietza** [comment]
@danmarsden I think these changes have been implemented now, so I believe this issue can be closed? Thanks for the enhancements!

**Comment by danmarsden** [comment]
great - thanks.
