### ISSUE TITLE
Setting for corresponding calendar events

### ISSUE THREAD

**Issue by haietza** [danmarsden/moodle-mod_attendance#269]
It looks like with 3.1, you added a feature wherein a calendar event is created for each attendance session that is added. Our faculty find this cumbersome, in that it forces other events out of the event block (for things like quizzes, assignment due dates, etc). I know there was some discussion of making this a setting that an admin could either enable or disable - we would love to see that added to the plugin so we could disable the adding of calendar events for attendance. Thank you!

**Comment by danmarsden** [comment]
There is a general push in Moodle to include dates for all events in the calendar and Moodle 3.2 comes with improvements to the my moodle page particularly around showing of events etc.

The calendar API in Moodle doesn't currently allow us to hide certain modules events from students, but personally I think this is probably something that should be part of the Moodle core calendar API - allowing events from any module to be hidden from students - rather than implemented within a specific activities code.

I'm always open to receiving funding to improve the attendance plugin, but implementing a setting to control this within the attendance code is not something I'm planning to do so am closing this as "won't fix" - feel free to get in touch if you would like to provide funding to help work on a solution for this though. (I work for the Moodle Partner Catalyst IT)

**Comment by haietza** [comment]
@danmarsden Wow, thank you SO much for adding this setting Dan! Our faculty will be so happy! We really appreciate the addition.

**Comment by danmarsden** [comment]
Thanks - I received some funding from an existing client to help complete this work along with the new at-risk students reporting and various other improvements.
