### ISSUE TITLE
Students can not mark their attendance before course enrolment (feature request)

### ISSUE THREAD

**Issue by miroi** [danmarsden/moodle-mod_attendance#282]
Dear experts,

usually, I am setting up the attendance module so that students mark their attendance themselves, outside session times.

It happens, however, that when I prepare sessions for the whole semester (for 13 weeks, each week has one session), some (lazy) students start enroling the Moodle course in delay, after 1. or 2. week. In such case, the attendance module, unfortunately, does not allow students to mark thier attendance before the course enrolment, and the teacher has to do it manually.

Is there a remedy for that, or, could it be new feature ?

**Comment by danmarsden** [comment]
I think this is really an issue with your enrolment procedure rather than the attendance plugin - it would be better for you to tell your students they won't get graded for attendance unless they enrol or find a way of automatically enrolling users. This isn't something I plan to change in the attendance plugin. Thanks.

**Comment by danmarsden** [comment]
I should have also said - pull requests are always welcome and I'd probably consider something like this if it didn't impact the UI too much, but it does feel like a setting to control bad user behaviour or bad workflow instead of fixing the behaviour or workflow itself.

thanks!

**Comment by miroi** [comment]
Fine, thanks the answer. Rather I have to find some workaround of students enrollment procedure....

**Comment by emmarichardson** [comment]
So I have a good use case for this.  I am using Moodle for event management for our teachers PD.  I set up attendance for the event and it would be nice if our attendees could check in a half hour before the event starts.  In fact, I have to currently set the attendance to start 5 minutes after the beginning of the event to stop it from hiding...it would be nice if you would give us the ability to disable this.  It is not going to encourage bad behavior if we are setting the attendance session time...

**Comment by danmarsden** [comment]
@emmarichardson  - that sounds different from the original report here.

The original reporter is basically saying they want to record attendance for users before they are enrolled in the course. The attendance list looks at the user enrolment date and makes sure they were enrolled in the course at the time of the attendance. If they are not enrolled, it doesn't show them in the list.

Taking attendance outside the "session time" is already possible but it is a site-wide setting rather than at the individual session level which is what I think you are asking for - new issue for that please :-)

**Comment by emmarichardson** [comment]
Sorry Dan, I misunderstood the post.  I have submitted a new request.

Emma Richardson
DL Coordinator
Direct: 719-775-4022

**Comment by danmarsden** [comment]
thanks!
