### ISSUE TITLE
Allow attendees to give apologies and comment in advance of a session.

### ISSUE THREAD

**Issue by iainhallam** [danmarsden/moodle-mod_attendance#300]
Being able to mark an actual attendance is great, but how do I know which students should be excused? It would be nice if they could set an expected attendance in advance to give apologies for a session so I know how many to expect. An optional (able to set as required?) comment to explain would be great, too.

**Comment by iainhallam** [comment]
To expand on this, our current spreadsheets record two values for the end of the course - attendance, exactly as produced at the moment - and commitment - the percentage of sessions that they either attended or sent apologies for. We notify only when a number of consecutive sessions are marked Absent without notice, rather than an overall percentage.

**Comment by danmarsden** [comment]
Hi Iain, sounds interesting.

By default self-marking of the attendance is only open during the session but you could change this with the admin level setting "studentscanmarksessiontime" and then set up a status for "apolgies" 
Teachers can already enter notes on each students attendance but this isn't currently available for students to use when self-marking. There might also be improvements you could make to the availability settings of the status so that the status for present is only available during the session time but "apologies" is available prior to the session opening.

So yes, there are some things that could be done to improve how you would manage this but I can't see this happening in my volunteer time - feel free to submit a pull request with improvements or contact me privately if you are interested in funding my time to improve the plugin to meet your needs.

thanks,

**Comment by nwp90** [comment]
Dan,

We now have an urgent need for students to be able to report absence (but obviously not presence!) in advance, to make things bearable for admins over the next few months. The suggestion I have from users is that the status set definition should allow either a tick box to allow students to use a status before the session, or perhaps (although we can't see why it would be useful) to have an "opposite" setting to the existing one that specifies how long after a session a student can use the status.

I think the studentscanmarksessiontime option would probably not be useful in its current form at that point (we think it's probably not useful as a global at the moment, either, but that's a different question) - not sure what best answer would be there.

Anyway, proposal is basically to add an option for "before" to each status that would be checked in the same way as the existing option for "after". Whether it's a tickbox yes/no or a time, we're open to input.

Would obviously prefer to get your input before going ahead...


Cheers,


Nick

**Comment by danmarsden** [comment]
Sounds good thanks Nick!

I think a simple checkbox is probably fine for "first version".

I'm just thinking that we might need to be careful about the auto-grading stuff not selecting it and we might need to make sure that it's really obvious to students - eg what happens when a student is early, brings up the take attendance form but only has "absent" listed as an option - I can see a few students not even reading the options and submitting the form.

But.. I'm happy for the UX to be improved later once we see how students/teaching staff engage with the new option.

**Comment by nwp90** [comment]
Haven't yet had time to work on this; still keen though.

**Comment by danmarsden** [comment]
first version to allow students to report an absence is now in the 4.1 codebase - still to come are some improved behat tests and also some UI changes so that students don't get "submit attendance" as a link but "report future absence" or something similar.

dealing with "comments" is outside the scope of this work for now but if someone is really interested in seeing that implemented (and wants to fund the development) feel free to reach out!
