### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by dinism** [danmarsden/moodle-mod_attendance#317]
![imagem](https://user-images.githubusercontent.com/14828021/42626109-5701957c-85c1-11e8-9c09-ff94de19a909.png)

**Comment by danmarsden** [comment]
&helip is a typo which I've just fixed in the github branches for versions 3.1 and higher.

You cannot delete statuses that are in-use, The attendance will have recorded sessions with users that have those statuses. You will need to delete existing user attendance data in the attendance before you can delete the statuses. (or just use the hide option to hide the status from view when marking new attendances.)

In future - for asking questions, please use the community forums on moodle.org:
https://moodle.org/mod/forum/view.php?id=741
