### ISSUE TITLE
Site-wide reporting on attendance data

### ISSUE THREAD

**Issue by aspark21** [danmarsden/moodle-mod_attendance#373]
Thanks Dan for this really useful plugin!

We have some needs for better reporting on a site-wide basis. Thinking it might have to be in a separate report plugin.
- for a particular user site-wide (i.e. what is the student's attendance record across all the modules they are taking?)
- on an aggregated basis what is the attendance record for all the students in the courses for a particular category (category = department/faculty in practical terms)

**Comment by danmarsden** [comment]
Hi Alastair, I've been hoping that Moodle core will implement a better reporting engine at some point so that we can leverage this for displaying reports. I see the new Moodle for Workplace product is coming with a new reportbuilder tool but it doesn't sound like the code for this will be publicly available or usable in a standard Moodle site - hopefully that changes at some point and we can make use of it. In the meantime the best option for custom reporting like this is to use the sql-based reporting plugins that are currently available for Moodle.

Of course - pull requests and funding are always welcome :-)

**Comment by nwp90** [comment]
@danmarsden FYI - The first part of this appears to be pretty much what I've been working on

**Comment by nwp90** [comment]
See https://github.com/nwp90/moodle-mod_attendance/tree/nwp90-allsessionsreport for work in progress. @danmarsden - would appreciate thoughts at this point.

**Comment by donhinkelman** [comment]
Sorry, I don't know to do a pull request, but I am glad site-wide reporting is being added. Here is a link to the [Site Attendance Block](https://moodle.org/mod/forum/discuss.php?d=260173) that I helped develop over five years ago. Its main purpose is to identify students-at-risk of failing due to poor attendance, so it only reports absences. I hope that capability will be built into the new feature being discussed here.

**Comment by danmarsden** [comment]
Hi Nick - Sorry I haven't had a chance to look at this - make sure you file a pull request when you want me to review it, but it might be a few more weeks before I'm able to look properly - hope all is going well! - @donhinkelman it sounds like you might not have seen some of the existing reporting on at-risk students - it might be worth you taking a look at the recent versions which let you set "warning sets" with email notifications when users drop below set values.

**Comment by nwp90** [comment]
Dan - thanks for update. Will do a bit more work on it first in that case...

**Comment by danmarsden** [comment]
Hey Nick!

just giving this a go today and spotted:

Notice: Undefined index: sesscourses in /mod/attendance/classes/event/session_report_viewed.php on line 85

Notice: Undefined offset: 1 in /mod/attendance/renderer.php on line 2000

any chance you could tidy those up?

thanks!

**Comment by danmarsden** [comment]
closing this one - it should now be possible using the new 4.0 reportbuilder source that just landed - would be good to get some feedback on that if you get a chance to see if it has all the fields you need.

thanks!

**Comment by donhinkelman** [comment]
I would also be interested in reading that feedback, on how the 4.0 report builder can do site-wide reports of attendance.

**Comment by danmarsden** [comment]
Hey @donhinkelman - I've added a new custom report source in the latest version of the attendance code - if you have a 4.0 site and the latest version of the attendance plugin you can find the new report source in the drop list available in the admin > reports > report builder > custom reports > Add new report.

thanks!
