### ISSUE TITLE
We can print the QR code on students ID card which will have attached or inbuilt RFID .

### ISSUE THREAD

**Issue by agasheaditya** [danmarsden/moodle-mod_attendance#375]

**Comment by agasheaditya** [comment]
So whenever student will enter in the class the link for specific QR code will get activated and then only we can scan the ID card and mark the attendance .
That will result in less fake attendance marking and also we can locate a particular student via tracking a RFID last scan in specific lab or class room.

**Comment by danmarsden** [comment]
Hi There, 

thanks for the suggestion, but I don't think that printing/generating id cards is something that the attendance plugin should be responsible for. This is something that an organisations student management system should provide.

There are some organisations that do this already and have a scanner set up which then use webservices or other methods to update the Moodle attendance for a session.

This involves custom hardware (scanner) within each room and integration with the student management system to read the card, identify the student and pass information about this back to Moodle.

I'm sure there are probably improvements we could make in the attendance plugin to make this process easier, but I also suspect you are suggesting this as part of your investigation as a GSOC student. I would prefer improvements like this to be driven by a school/university that want to implement this and want to help design a solution that works - rather than some developers trying to guess what is required.

I'm closing this for now, but I'm happy to re-open if an organisation that wants improvements related to this can provide a bit more information about what they actually need from the Attendance code, and what is provided by their custom hardware/student management system.

A heads-up - I'm unlikely to select this idea as a project idea for GSOC unless you provide a lot more detail (would probably require a full specification on the changes/improvements you would be adding to the attendance code) and an organisation that is going to actively help shape the requirements and would implement this feature in their organisation.

thanks!

**Comment by agasheaditya** [comment]
I think we should fetch the location of student's device while scanning the QR code. and also we can manage the activation and deactivation of QR codes by adding timings according to lecture plans .

**Comment by danmarsden** [comment]
Please spend some more time researching this. If you are hoping to make a gsoc application you will have a better chance of success by proposing a solution for the existing qr code project idea. It would be interesting to see a device location check, but you would need to prove that you understand how this would work for the attendance plugin including demonstrating that you have the skills required to implement this.

The attendance plugin has no concept of 'lecture plans' it would be good for you to learn the terminology used by the attendance plugin when writing your proposal. Thanks!

**Comment by agasheaditya** [comment]
sir, what should i do to define my point more clearly to you ? or where can i find the existing QR code application ?so that i can research on it and make some changes.

**Comment by danmarsden** [comment]
To be a successful GSOC applicant you must demonstrate your ability to research and discover information on your own. We expect that you should be able to install moodle and any other dependent plugins/tools required for your project. You should be able to find the "existing application" on your own.

**Comment by agasheaditya** [comment]
sir i've installed the plugin in my moodle setup till now, now should i try to make changes in that plugin code and compile ?
