### ISSUE TITLE
Cannot enable QR Code without filling Student Password field

### ISSUE THREAD

**Issue by maksudr** [danmarsden/moodle-mod_attendance#378]
A user can leave the "Student password" field empty and tick the "Include QR code" box and still save the session. This behaviour is misleading to the user and gives the impression that the attendance can be taken with the QR code only. The user will not see the option to display the QR code and has to troubleshoot to figure out that they must also fill in the Student Password field.

I believe the page should flag an error and prompt the user to fill in the student password field and not let the user save until the field has been filled.

A video demonstrating the bug:
[Video Link](https://gfycat.com/safespectacularhairstreakbutterfly)

**Comment by danmarsden** [comment]
Student self-selection should not require a password to be used. Some teachers set the session up so that users can self-mark without requiring a password. The use of the QR code in this case would just basically embed a url (it wouldn't need to change/rotate etc.) - If this isn't working then it would be a bug we'd need to fix, but we shouldn't force the session to require a password when using the QR Codes.

thanks!

**Comment by maksudr** [comment]
Hi @danmarsden, 

I was aware that student self-selection should not require a password but was not aware that the QR codes without a password were a feature. (though makes complete sense)  I'll be looking to clarify these features in the documentation too if selected for GSoC. 

Thanks for clearing this up!

**Comment by maksudr** [comment]
Hi @danmarsden,

I have pushed a fix for this in the PR above. Let me know your thoughts.

Cheers!
