### ISSUE TITLE
default studentavailability is 0.

### ISSUE THREAD

**Issue by Xiphias0404** [danmarsden/moodle-mod_attendance#387]
When add a new status, I leave studentavailability nothing, and click add, then the new status' studentavailability woudl be 0, that's not what we expected, and the default value in code is null, so I think that's a bug.

I add
if(empty($newstudentavailability))
                $newstudentavailability = null;
in preferences.php ln72 can fix this, but maybe there is another better way to fix this.

**Comment by danmarsden** [comment]
This is expected behaviour - When the student availability field is empty (null) it means that the item is always available to students. the value 0 means that the new status value is not available for selection.

Student availability is a feature that is not used by everyone - so the default value (null) making it always available seems to make sense to me.

I'm sure there are probably improvements we can make to the UI to make this clearer to the teacher/admin setting up the status - I'm closing this but if you can think of ways to improve the UI to make this clearer feel free to create a new issue describing the changes you think should be made to improve the UX.

Feel free to help work on this and submit a pull request too!
