### ISSUE TITLE
Improve QR code password handling

### ISSUE THREAD

**Issue by RStumbur** [danmarsden/moodle-mod_attendance#424]
Trying to use the new QR Code feature, but in order to generate the QR Code, the password must be enabled and entered, which is OK, but then the generated QR Code and URL both have the password visible. A student in class can easily pass along to an absent student the password or the URL to use to enter themselves as Present, which defeats the purpose of attendance. 

Or am I missing something?

**Comment by danmarsden** [comment]
yes - the QR code rotation feature recently implemented is really the "first release" of this functionality and needs further improvement. I haven't created issues for these planned improvements so thanks for creating this here.

as mentioned in the comments on #414 - We shouldn't present the internal text password at all, and if "Automatically select highest status available" is selected we should just save the attendance rather than presenting them with a form to submit. 

Hopefully that will come in future! - thanks for the report! :-)
