### ISSUE TITLE
Participant's names do not show up on attendence list

### ISSUE THREAD

**Issue by cord-sys** [danmarsden/moodle-mod_attendance#521]
This is what my colleague wrote me about "groups":
Every LDAP group corresponds theoretically to a learning group, provided that there is a course in which they are enrolled.

Moodle 3.10.1+ (Build: 20210219) is used. The presence plugin mod_attendance 3.9.1 (2020120300). 

So the students have all been enrolled into the LDAP group and into the course, BEFORE the attendence plug-in was added to the course's website.
Still, some of the participants' names have disappeared from the attendance list.
(This post is related to the former posts #518 and #520 which have been closed unsolved because of lack of information.)

**Comment by danmarsden** [comment]
as mentioned in #518 and #520...

Can you please create a new post in the moodle.org community forums with more details on what you are trying to do here? - make sure you mention the Moodle version you are using, and the attendance plugin version you are using.
here's a direct link to the attendance forum - please create a post there:
https://moodle.org/mod/forum/view.php?id=741

Please make sure you have also checked the course groups themselves to ensure the students that you are missing in the list are still in the course group - and not just the participant list in the attendance session. If they aren't in the course groups anymore due to some failure with your automatic groups, they won't show in the attendance session either.

thanks!

**Comment by cord-sys** [comment]
From what you keep answering to my now third post, it seems like you are not really interested in solving the issue.
Are you sure, you're doing the right job?

**Comment by danmarsden** [comment]
I think I've been quite polite. You don't seem to be understanding my response or understanding the nature of open source.

You are asking for help in the wrong place. The right place to ask for free help is in the community forums I have linked to.

If you look in the forums you will see I give away a lot of my free time to help there too.

Keep in mind that I do this as a volunteer - I give away this code for free. Do you work for free too?

**Comment by cord-sys** [comment]
To ask for more information and close the same issue at the same time is 
never polite, especially if you're doing this several times.

Please keep in mind that English is not my mother tongue. Apart from in 
your very last message, you did not say clear enough that this was the 
wrong forum.

And yes, I work for free, too, as I am not responsible for solving IT 
issues at the school I work for. I don't get any extra pay, but I pay 
for this with my free time, too.

---

Am 14.03.2021 10:24, schrieb Dan Marsden:

> I think I've been quite polite. You don't seem to be understanding my 
> response or understanding the nature of open source.
> 
> You are asking for help in the wrong place. The right place to ask for 
> free help is in the community forums I have linked to.
> 
> If you look in the forums you will see I give away a lot of my free 
> time to help there too.
> 
> Keep in mind that I do this as a volunteer - I give away this code for 
> free. Do you work for free too?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] 
https://github.com/danmarsden/moodle-mod_attendance/issues/521#issuecomment-798875242
[2]

**Comment by danmarsden** [comment]
They were closed because you were asking for help in the wrong place I suggested that in your community forum post you provided more information than you have here because if you copied the sa.e text into a mpodke forum post no one would have been able to help you there either.

Asking someone if they are in the 'right job' is no
