### ISSUE TITLE
time in different format

### ISSUE THREAD

**Issue by franszwijnenberg** [danmarsden/moodle-mod_attendance#524]
How can I chance the time display format from AM/PM to a 24 hour clock
![image](https://user-images.githubusercontent.com/75476440/114891487-37544d80-9e0c-11eb-9aff-04ac6cf227ca.png)
when I enter the time in a 24 hour format
![image](https://user-images.githubusercontent.com/75476440/114891629-5521b280-9e0c-11eb-8788-ba1fb1d3e3cc.png)

**Comment by danmarsden** [comment]
Time formatting is configured in Moodle (and attendance) using language strings - so that each language can implement it's own formatting of a string.

You can edit how this displays in your site using the language customisation tool within Moodle:
https://docs.moodle.org/310/en/Language_customisation

From memory it's the "strftimeh" and "strftimehm" strings within the attendance.php lang pack that control the display of those ones.

If you have any more questions around this - please ask for help in the attendance forum on moodle.org - the github tracker is really for bug reports/feature requests, rather than "how do I" style questions:
https://moodle.org/mod/forum/view.php?id=741

thanks!

**Comment by danmarsden** [comment]
also - see: https://www.php.net/manual/en/function.strftime.php for a list of the strftime format options
