### ISSUE TITLE
Diplay time hard coded

### ISSUE THREAD

**Issue by franszwijnenberg** [danmarsden/moodle-mod_attendance#527]
In mod_attendance version 2020120300 the start- and end time are displayed in 12 hour format while the input is in a 24 hour format which is my default calendar setting
![image](https://user-images.githubusercontent.com/75476440/117132842-b00f4f80-ada3-11eb-82f0-51338776bb4e.png)
This occurs both in  Moodle Workplace 3.10.3 with PHP version 7.2.24 and Moodle LMS 3.9.6 with PHP version 7.2.24
Can you fix it so that the display of the time also follows the calendar settings
Kind Regards
Frans Zwijnenberg

**Comment by danmarsden** [comment]
Hi there, 

Display of times/dates in Attendance is controlled using the lang strings - you can change these yourself by using the language customisation UI in your Moodle site - select the language in use, and in the attendance.php lang file look for the "strft" items here:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/lang/en/attendance.php#L542-L549

I don't have any current plans to change this, but feel free to get in touch privately if you would like to fund improvements, otherwise pull requests are also welcome.

thanks!
