### ISSUE TITLE
Daylight Saving Time causes wrong timestamps in database

### ISSUE THREAD

**Issue by wiktorwandachowicz** [danmarsden/moodle-mod_attendance#536]
In many countries across Europe and elsewhere a DST (Daylight Saving Time) changes happen twice a year
* https://en.wikipedia.org/wiki/Time_in_the_Czech_Republic
* https://www.timeanddate.com/time/change/czech-republic/prague

This year 2021 the changes are:
1. on March 27-28 (Saturday-Sunday) - at 02:00 CEST clocks were turned forward 1 hour to 03:00 CEST
2. on October 30-31 (Saturday-Sunday) - at 03:00 CEST clocks are turned backward 1 hour to 02:00 CEST

During the day when such change happens, attendance settings and time calculations result in wrong timestamps to be saved in database. For example:

1. A session created on March 28, 2021 from 01:00 to 01:55 is displayed correctly (1AM - 1:55AM)
2. But session created on on March 28, 2021 from 02:00 to 04:00 is displayed incorrectly (3AM - 5AM)

See attached images:
* **attendance-group1-correct.png**
![image](https://user-images.githubusercontent.com/1437510/123632935-d20fd600-d818-11eb-823e-207a44404e51.png)
* **attendance-group2-incorrect.png**
![image](https://user-images.githubusercontent.com/1437510/123633060-01264780-d819-11eb-96ee-394cfa0bdc74.png)
* **attendance-review.png**
![image](https://user-images.githubusercontent.com/1437510/123632981-e3f17900-d818-11eb-86df-90ce0ae8faa9.png)

**Comment by danmarsden** [comment]
Thanks for the report - this is due to the way the "duration" form element is handled in the attencance plugin - instead of using a start/close date like you see in assignment and other activities, the original developer implemented this as a "duration" field.

The "start date" is calculated at midnight so you end up getting it generating "before" Daylight savings comes into effect.

There's probably a bit of work re-organising this properly and as daylight savings typically happens on a Sunday most of the clients I have using Attendance aren't affected because the majority of their sessions happen during the week so I don't think this is something I'll be able to priotise as a volunteer. Feel free to submit a pull request or get in touch privately if you'd like to help fund improvements to the attendance plugin.

thanks!

**Comment by danmarsden** [comment]
this has come up before, but I couldn't see this listed in the current list of open bugs - maybe it was reported in the forums...

**Comment by wiktorwandachowicz** [comment]
The "duration" form element is not a problem, but the way the start of session date is calculated. In the case of multiple sessions everything seems to work (sic!) because of a call to Moodle `make_timestamp()` function. But for single session a direct calculation of timestamp was used so far - present at the top of `attendance_construct_sessions_data_for_add()` function.

Member of my team was able to prepare a fix, which is to use `make_timestamp()` to calculate correct timestamp - taking into account timezones and DST (Daylight Saving Time) for both cases: multiple sessions and single session too.

So there goes the proposal of fix for several branches, starting with Moodle 3.6 up to Moodle 3.11:

- MOODLE_36_STABLE - https://github.com/danmarsden/moodle-mod_attendance/pull/561
- MOODLE_37_STABLE - https://github.com/danmarsden/moodle-mod_attendance/pull/562
- MOODLE_38_STABLE - https://github.com/danmarsden/moodle-mod_attendance/pull/563
- MOODLE_311_STABLE - https://github.com/danmarsden/moodle-mod_attendance/pull/564

**Comment by danmarsden** [comment]
awesome - nice work tracking that one down! - I'll try to review that within the next week or so and merge it in.

thanks!

**Comment by wiktorwandachowicz** [comment]
Pull requests seem to be merged around 24 days ago. Can we close this issue then?

**Comment by danmarsden** [comment]
yeah - thanks for the reminder!
