### ISSUE TITLE
QR Code self marking - error messages

### ISSUE THREAD

**Issue by kimberley-johnston** [danmarsden/moodle-mod_attendance#543]
Hi,

We've been using the attendance mod (thank you!) and have recently been trialling using QR codes to have our students self mark their group sessions. We've run into a couple of teething issues and one of them seems to be if a student attempts to scan into a group session when they're not a member of the group. Rather than getting a failure message they get the success message and no attendance is recorded. 

Is it possible to catch that particular error and show a different message for the students? 

We're currently using Moodle 3.10.5+ with Attendance 3.9.3

**Comment by danmarsden** [comment]
thanks for the report - that does sound like a bug! - I'm quite busy at the moment and don't have a lot of volunteer time to spread across all the things at the moment - but if you have internal development capabilities feel free to submit a pull request, otherwise I'll try to get to this at some point!

thanks,

**Comment by kimberley-johnston** [comment]
Cheers Dan - I'll see what I can do re: internal development.

**Comment by nwp90** [comment]
Working on it...
