### ISSUE TITLE
intermittent test failure

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-mod_attendance#607]
There was 1 failure:

1) mod_attendance_external_testcase::test_get_session_with_group
Failed asserting that 0 matches expected '266000'.

/var/www/html/mod/attendance/tests/externallib_test.php:207
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

**Comment by micaherne** [comment]
Hi Dan, we're having a lot of trouble with this unit test failing and it looks like it can fail if it starts in the hour before midnight due to this line: https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_401_STABLE/tests/external/external_test.php#L198

I'm not sure what the best fix is but changing it from 3600 to 1 reduces the chances of it happening.

**Comment by danmarsden** [comment]
Good call - I've made that change in all supported branches here in github - thanks! :-)

**Comment by micaherne** [comment]
Great, thanks Dan!
