### ISSUE TITLE
Problem importing sessions

### ISSUE THREAD

**Issue by avillegasic** [danmarsden/moodle-mod_attendance#654]
Hello!

When I try to import sessions from: Site administration - Plugins - Activity modules - Manage activities - Import Sessions I get the following error: https://ibb.co/7JjKpX3

Sometimes it works without problems, other times, I have to try 3 times with the same csv file and it works, other times it doesn't work completely. I don't understand why, the classes are new, I add the attendance activity completely blank, and again sometimes it works sometimes it doesn't work.

What Moodle version are you using?: Moodle 3.8.9
What version of the Attendance plugin do you have installed?: 3.9.1

**Comment by danmarsden** [comment]
Hi there, 

support for Moodle 3.8 ended almost 2 years ago and the version of Attendance you have installed is not even the latest version available for that release.

Unfortunately I'm not in a position to support older Moodle releases - but if you find this issue with a supported Moodle version and the latest version of the attendance plugin for your Moodle version feel free to report this again - otherwise you might want to contact a local Moodle Partner who may be able to help support you with an older Moodle release - thanks!
