### ISSUE TITLE
Attandance on mobile app is having error with moodlecloud.com hosting.

### ISSUE THREAD

**Issue by aliallawati** [danmarsden/moodle-mod_attendance#700]
Hi,
i am moodlecloud.com user with Premium plan, i am trying to use "Attendance" Activity/Plugin to submit student attendance through moodle app, 
when i select the appropriate class> attendance activity> select session (submit attendance button) , i get an error "template has some errors and can not be displayed"

Need your support to fix the issue, our teachers are depending on the app to record student attendance
Thank you.
Ali

![select_session_in_app](https://github.com/danmarsden/moodle-mod_attendance/assets/145115578/89db321c-d8fa-4a33-9796-831a0ae03289)

<img width="327" alt="err" src="https://github.com/danmarsden/moodle-mod_attendance/assets/145115578/a34934f5-d3d8-4f5e-9348-e16dd6ae1ad6">

**Comment by danmarsden** [comment]
Hi @aliallawati - thanks for the report, sounds like a recent change to the app or to the version of the attendance plugin installed on moodlecloud.com has an issue as this definitely used to work - pinging @jleyva FYI - I'm not sure I'll get time to look into this in the short term so any further help anyone can give to identify this issue would be useful.

thanks!

**Comment by jleyva** [comment]
@dpalou is this error caused by the server, particularly, the moustache template not properly rendering?

**Comment by dpalou** [comment]
Hi @danmarsden , I was able to reproduce the error in a local site and it seems to be an error in the plugin's code.

The template returned by the plugin contains an empty (ionSelect), and Angular doesn't allow that so an error is thrown:

`<ion-radio-group [(ngModel)]="CONTENT_OTHERDATA.statusall" (ionChange)="">`

I debugged it a bit, and the list of users [in this line](https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_402_STABLE/classes/output/mobile.php#L424) is empty. This means that `$data['selectall']` is an empty string, and it causes this error.

I don't know the attendance plugin's code and use cases enough to fix this myself. E.g. I don't know if the problem is that this line should always return users but now it isn't for some reason, or this is a real use case that isn't treated properly.

**Comment by danmarsden** [comment]
thanks heaps @dpalou - that's really useful - This is pretty high on my list of things to look at but of course it will need to be done in my "free time" which is not easy to find... :-) happy for anyone else to dig further and send a pull request though!!
