### ISSUE TITLE
remove student from a group changes session attendance already taken

### ISSUE THREAD

**Issue by ciberlook** [danmarsden/moodle-mod_attendance#716]
Hi there,
My version of Moodle is: 4.1.3+ (Build: 20230427)
And the attendance plugin version is: 2023020107

The problem I have is that I need to link each session to groups, so that sometimes students can attend in the 'morning group' and others in the 'afternoon group'. Once the attendance has been already taken, if I remove a student from a group because I need to reassign him in a different one, previous sessions also changes and I lose the information.
For example, If I have a student that usually attend the course in the morning, when I remove him from the morning group and I put him in the afternoon, all sessions where he appears changes losing his attendance information.
Am I doing something wrong?
PD: I cant have the scenario where a student could be in two groups at the same time. I know it is possible but is not what I am looking for.
Thank you in advance!

**Comment by danmarsden** [comment]
unfortunately this isn't something that is supported by Moodle - groups in Moodle are static and the history of group membership is not something we can access - you are a member of the group or you aren't and there's no way for the attendance activity to ask "What group was the user in on date XYZ"

I'm closing this as "won't fix" because to do this would be a lot of work and it's not something that Moodle itself supports, but... I'd be happy to revisit this if someone sent a Pull request through, or decided they wanted to fund the development required to add this (it would likely need a decent budget.)

thanks!
