### ISSUE TITLE
More Explanation_Attandance 

### ISSUE THREAD

**Issue by frs2022** [danmarsden/moodle-mod_attendance#729]
Dear All,

Can anyone help me understand this issue:

I have an attendance activity in moodle and allow students to record their attendance by themselves using password as following settings in attached file:

![005](https://github.com/danmarsden/moodle-mod_attendance/assets/117255482/c8a2465b-64de-4ae0-b360-42c1b16822f1)

And the attendance report shows for students, as some are **self recorded** and others are **system auto recorded**. Can any help me understand? why there system auto record to "present" status for one students and other students are self-recorded?

**Comment by danmarsden** [comment]
Hi there - can you please create a new forum post in the moodle.org attendance forum for this?
https://moodle.org/mod/forum/view.php?id=741

make sure you include a screenshot of the status set settings for this attendance as well - The tracker here in github is really for reporting bugs rather than asking for help - I'll keep an eye out for your post in the forums - thanks!
