### ISSUE TITLE
String not in lang

### ISSUE THREAD

**Issue by eduardokraus** [danmarsden/moodle-mod_attendance#774]
![Captura de Tela 2024-10-24 às 14 48 42](https://github.com/user-attachments/assets/2a993212-a256-48aa-b2fc-6789854c58b1)

**Comment by danmarsden** [comment]
Hey @eduardokraus thanks for the report!

This is actually intentional as per the phpdoc comment, the get_description function inside an event class is supposed to contain an English string and not a translated string. This helps to unify log reporting and only the 'name' of the event is localised in the get_name() function. I couldn't find any dev docs that explain this well but you can see other examples in the event classes inside moodle core plugins too.
