### ISSUE TITLE
Viewing Attendances with Parent Role not working

### ISSUE THREAD

**Issue by leondasonora** [danmarsden/moodle-mod_attendance#84]
When I logon as a parent any place I select to view the attendance I get the following error.
 
Sorry, but you do not currently have permissions to do that (Viewing Attendances)

I have checked the role permissions and I haven given my parent role allow permission for Viewing Attendances. 

Student, Teacher, Administrator access to student attendance works as it should. 

Is there something I'm overlooking?

**Comment by danmarsden** [comment]
I haven't tried to configure this myself as I'm relatively new as the maintainer and I don't actively use this plugin myself (I just fix bugs and try to provide a level of support)

It looks like it should be possible to view the reports like Dimitriy mentions here:
https://moodle.org/mod/forum/discuss.php?d=110398#p487540

but I'm not sure if support for parents has been added completely in all locations - others here might know more than me?

**Comment by danmarsden** [comment]
Took a look at this today - Parents can view the data in the grades report but cannot see the complete or overview reports due to the core use of the view Capability.

I've created a tracker issue to see if there's a way around this because deleting the attendance:view capability is not really a viable option.
https://tracker.moodle.org/browse/MDL-53500

**Comment by danmarsden** [comment]
I've proposed a patch for Moodle that fixes this - there's nothing I can do within the attendance code to make this work and it is really a "Core" bug and not an issue with attendance. So closing this one off (feel free to add yourself as a watcher to the Moodle core bug and monitor progress there!)
